### ISSUE TITLE
Error: Cannot find module ...

### ISSUE THREAD

**Issue by filly82** [atom-ide-community/atom-script#1515]
Just updated to the latest version ( I don't know what version I Had before) and the simplest script is not working anymore

this is the error
axios is a locally installed script, it fails just at requiring it

`module.js:557
    throw err;
    ^

Error: Cannot find module 'axios'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at [stdin]:3:15
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:152:38)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (module.js:660:30)
    at evalScript (bootstrap_node.js:475:27)`

**Comment by michalczwarno** [comment]
i have the same problem. Did anybody find solution? it seems that happens after upgrade to certain version
