### ISSUE TITLE
Uncaught Error: Cannot find module './grammar-utils'

### ISSUE THREAD

**Issue by maixianyu** [atom-ide-community/atom-script#1872]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.36.1 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.18.1

### Stack Trace

Uncaught Error: Cannot find module './grammar-utils'

```
At module.js:545

Error: Cannot find module './grammar-utils'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.36.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:154765)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:146072)
    at /packages/script/lib/script.js:13:21)
    at /packages/script/lib/script.js:277:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:146782)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:150329)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:1:674931)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:3186823)
    at Package.activateConfig (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:3176182)
    at PackageManager.t.exports.PackageManager.packageHasSettings (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:892642)
    at PackageCard.hasSettings (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:14:3028659)
    at PackageCard.updateSettingsState (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:14:3018939)
    at PackageCard.updateInterfaceState (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:14:3018762)
    at ~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:14:3026892
    at ~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:14:3028910
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:1172164)
    at Emitter.emit (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:1173605)
    at PackageManager.t.exports.PackageManager.emitPackageEvent (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:901822)
    at ~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:899231
    at r (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:893761)
    at o (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:14:1032937)
    at ChildProcess.n.process.on.e (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:14:1033143)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
     -3:10.7.0 core:confirm (input.hidden-input)
     -0:05.3.0 core:cancel (div.package-detail)
```

### Non-Core Packages

```
linter 2.3.0 
linter-python 3.1.2 
linter-python-pep8 0.2.0 
script 3.18.1 
```

**Comment by maixianyu** [comment]
when i try to install package "script", the warning comes up.

**Comment by vampymaria** [comment]
same error
