### ISSUE TITLE
Installing “script@3.18.1” failed.

### ISSUE THREAD

**Issue by xxoo9898** [atom-ide-community/atom-script#1898]
C:\Users\HP\AppData\Local\atom\app-1.38.0\resources\app\apm\lib\install.js:288
            if (body.releases.latest) {
                              ^

TypeError: Cannot read property 'latest' of undefined
    at C:\Users\HP\AppData\Local\atom\app-1.38.0\resources\app\apm\lib\install.js:288:31
    at Request._callback (C:\Users\HP\AppData\Local\atom\app-1.38.0\resources\app\apm\lib\request.js:56:22)
    at Request.self.callback (C:\Users\HP\AppData\Local\atom\app-1.38.0\resources\app\apm\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\HP\AppData\Local\atom\app-1.38.0\resources\app\apm\node_modules\request\request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\HP\AppData\Local\atom\app-1.38.0\resources\app\apm\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)

**Comment by Mohamedebouguerra** [comment]
> C:\Users\HP\AppData\Local\atom\app-1.38.0\resources\app\apm\lib\install.js:288
> if (body.releases.latest) {
> ^
> 
> TypeError: Cannot read property 'latest' of undefined
> at C:\Users\HP\AppData\Local\atom\app-1.38.0\resources\app\apm\lib\install.js:288:31
> at Request._callback (C:\Users\HP\AppData\Local\atom\app-1.38.0\resources\app\apm\lib\request.js:56:22)
> at Request.self.callback (C:\Users\HP\AppData\Local\atom\app-1.38.0\resources\app\apm\node_modules\request\request.js:185:22)
> at emitTwo (events.js:126:13)
> at Request.emit (events.js:214:7)
> at Request. (C:\Users\HP\AppData\Local\atom\app-1.38.0\resources\app\apm\node_modules\request\request.js:1161:10)
> at emitOne (events.js:116:13)
> at Request.emit (events.js:211:7)
> at IncomingMessage. (C:\Users\HP\AppData\Local\atom\app-1.38.0\resources\app\apm\node_modules\request\request.js:1083:12)
> at Object.onceWrapper (events.js:313:30)

Did you find an answer for this error ?

**Comment by xxoo9898** [comment]
no，but I start to use vscode 

发自我的 iPhone
