### ISSUE TITLE
Uncaught Error: Cannot find module './grammars/database.coffee'

### ISSUE THREAD

**Issue by Skribinto** [atom-ide-community/atom-script#1909]
Just wanted to install "script". But nothing happens. At the second try, the error was thrown...

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Ubuntu 18.04.2
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.18.1

### Stack Trace

Uncaught Error: Cannot find module './grammars/database.coffee'

```
At module.js:545

Error: Cannot find module './grammars/database.coffee'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:155156)
    at Module.require (/app.asar/static/index.js:53:43)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146462)
    at /packages/script/lib/grammars.js:25:31)
    at /packages/script/lib/grammars.js:90:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146462)
    at /packages/script/lib/code-context-builder.js:17:17)
    at /packages/script/lib/code-context-builder.js:158:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146462)
    at /packages/script/lib/script.js:9:27)
    at /packages/script/lib/script.js:277:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (internal/module.js:11:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:686762)
    at Package.requireMainModule (/usr/share/atom/resources/app/static/<embedded>:11:3428177)
    at Package.activateConfig (/usr/share/atom/resources/app/static/<embedded>:11:3417536)
    at PackageManager.t.exports.PackageManager.packageHasSettings (/usr/share/atom/resources/app/static/<embedded>:11:928165)
    at PackageCard.hasSettings (/usr/share/atom/resources/app/static/<embedded>:14:2559807)
    at PackageCard.updateSettingsState (/usr/share/atom/resources/app/static/<embedded>:14:2550087)
    at PackageCard.updateInterfaceState (/usr/share/atom/resources/app/static/<embedded>:14:2549910)
    at /usr/share/atom/resources/app/static/<embedded>:14:2558040
    at /usr/share/atom/resources/app/static/<embedded>:14:2560058
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1206583)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1208024)
    at PackageManager.t.exports.PackageManager.emitPackageEvent (/usr/share/atom/resources/app/static/<embedded>:11:937622)
    at /usr/share/atom/resources/app/static/<embedded>:11:934754
    at r (/usr/share/atom/resources/app/static/<embedded>:11:929284)
    at n (/usr/share/atom/resources/app/static/<embedded>:14:1119363)
    at t.bufferStream (/usr/share/atom/resources/app/static/<embedded>:14:1119517)
    at Socket.e.on (/usr/share/atom/resources/app/static/<embedded>:14:1118119)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

### Commands

```
  6x -2:05.2.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
script 3.18.1 
```

**Comment by Skribinto** [comment]
... the package was installed. Perhaps there was a problem with my second try.
