### ISSUE TITLE
Uncaught TypeError: Cannot read property 'remove' of undefined

### ISSUE THREAD

**Issue by mjstaw** [atom-ide-community/atom-script#2006]
[Enter steps to reproduce:]

1. Press escape.

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.14.6
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.25.0

### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of undefined

```
At /Users/mjstaw/.atom/packages/script/node_modules/atom-message-panel/lib/MessagePanelView.js:189

TypeError: Cannot read property 'remove' of undefined
    at ScriptView.MessagePanelView.remove (/packages/script/node_modules/atom-message-panel/lib/MessagePanelView.js:189:30)
    at ScriptView.detach (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:5357:15)
    at ScriptView.removePanel (/packages/script/lib/script-view.js:89:10)
    at Object.closeScriptViewAndStopRunner (/packages/script/lib/script.js:161:21)
    at HTMLElement.coreCancel (/packages/script/lib/script.js:92:33)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349392)
    at KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1252536)
    at KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1248670)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:284598)
```

### Commands

```
     -0:20.9.0 editor:consolidate-selections (input.hidden-input)
     -0:20.9.0 core:cancel (input.hidden-input)
     -0:20.7.0 editor:consolidate-selections (input.hidden-input)
     -0:20.7.0 core:cancel (input.hidden-input)
     -0:20.6.0 editor:consolidate-selections (input.hidden-input)
     -0:20.6.0 core:cancel (input.hidden-input)
     -0:20.3.0 editor:consolidate-selections (input.hidden-input)
     -0:20.3.0 core:cancel (input.hidden-input)
     -0:20.1.0 editor:consolidate-selections (input.hidden-input)
     -0:20.1.0 core:cancel (input.hidden-input)
     -0:19.9.0 editor:consolidate-selections (input.hidden-input)
     -0:19.9.0 core:cancel (input.hidden-input)
     -0:19.7.0 editor:consolidate-selections (input.hidden-input)
     -0:19.7.0 core:cancel (input.hidden-input)
     -0:08.9.0 editor:consolidate-selections (input.hidden-input)
     -0:08.9.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-runner 2.7.1 
platformio-ide-terminal 2.10.0 
script 3.25.0 
```

**Comment by uqccha18** [comment]
I got the same error here:

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.25.0


### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of undefined

```
At C:\Users\chank\.atom\packages\script\node_modules\atom-message-panel\lib\MessagePanelView.js:189

TypeError: Cannot read property 'remove' of undefined
    at ScriptView.MessagePanelView.remove (/packages/script/node_modules/atom-message-panel/lib/MessagePanelView.js:189:30)
    at ScriptView.detach (/packages/script/node_modules/jquery/dist/jquery.js:5357:15)
    at ScriptView.removePanel (/packages/script/lib/script-view.js:89:10)
    at Object.closeScriptViewAndStopRunner (/packages/script/lib/script.js:161:21)
    at HTMLElement.coreCancel (/packages/script/lib/script.js:92:33)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:349392)
    at KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:1252536)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:1248670)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:284598)
```

### Commands

```
```

### Non-Core Packages

```
docker 0.8.0 
script 3.25.0 
vim-mode-plus 1.36.3 
```

**Comment by wesgt** [comment]
me too

**Comment by alexandergogl** [comment]
Same here.

```
/Users/alex/.atom/packages/script/node_modules/atom-message-panel/lib/MessagePanelView.js:189
Hide Stack Trace
TypeError: Cannot read property 'remove' of undefined
    at ScriptView.MessagePanelView.remove (/Users/alex/.atom/packages/script/node_modules/atom-message-panel/lib/MessagePanelView.js:189:30)
    at ScriptView.detach (/Users/alex/.atom/packages/asciidoc-image-helper/node_modules/jquery/dist/jquery.js:5357:15)
    at ScriptView.removePanel (/Users/Alex/.atom/packages/script/lib/script-view.js:89:10)
    at Object.closeScriptViewAndStopRunner (/Users/Alex/.atom/packages/script/lib/script.js:161:21)
    at HTMLElement.coreCancel (/Users/Alex/.atom/packages/script/lib/script.js:92:33)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349392)
    at KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1252536)
    at KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1248670)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:284598)
```

**Comment by Ilidumb** [comment]
Same thing.

**Atom:** 1.41.0 x64
**Electron:** 4.2.7
**OS:** Win10 Home
**Thrown From:** [script](https://github.com/rgbkrk/atom-script) package 3.25.0

C:\Users\Maks\.atom\packages\script\node_modules\atom-message-panel\lib\MessagePanelView.js:189
TypeError: Cannot read property 'remove' of undefined
    at ScriptView.MessagePanelView.remove (C:\Users\Maks\.atom\packages\script\node_modules\atom-message-panel\lib\MessagePanelView.js:189:30)
    at ScriptView.detach (C:\Users\Maks\.atom\packages\autocomplete-python\node_modules\jquery\dist\jquery.js:5357:15)
    at ScriptView.removePanel (file:///C:/Users/Maks/.atom/packages/script/lib/script-view.js:89:10)
    at Object.closeScriptViewAndStopRunner (file:///C:/Users/Maks/.atom/packages/script/lib/script.js:161:21)
    at HTMLElement.coreCancel (file:///C:/Users/Maks/.atom/packages/script/lib/script.js:92:33)
    at CommandRegistry.handleCommandEvent (C:\Users\Maks\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:349392)
    at KeymapManager.dispatchCommandEvent (C:\Users\Maks\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:1252536)
    at KeymapManager.handleKeyboardEvent (C:\Users\Maks\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:1248670)
    at WindowEventHandler.handleDocumentKeyEvent (C:\Users\Maks\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:284598)

**Comment by ljoxloyd** [comment]
Same thing.

[Enter steps to reproduce:]

1. Press Escape

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.25.0


### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of undefined

```
At C:\Users\lyuds\.atom\packages\script\node_modules\atom-message-panel\lib\MessagePanelView.js:189

TypeError: Cannot read property 'remove' of undefined
    at ScriptView.MessagePanelView.remove (/packages/script/node_modules/atom-message-panel/lib/MessagePanelView.js:189:30)
    at ScriptView.detach (/packages/script/node_modules/jquery/dist/jquery.js:5357:15)
    at ScriptView.removePanel (/packages/script/lib/script-view.js:89:10)
    at Object.closeScriptViewAndStopRunner (/packages/script/lib/script.js:161:21)
    at HTMLElement.coreCancel (/packages/script/lib/script.js:92:33)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:349392)
    at KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:1252536)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:1248670)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:284598)
```

### Commands

```
 12x -5:45.7.0 core:backspace (input.hidden-input)
     -2:25.3.0 script:run (input.hidden-input)
  2x -2:21.9.0 core:backspace (input.hidden-input)
     -2:18.5.0 editor:newline (input.hidden-input)
     -2:12.6.0 window:toggle-full-screen (div.am-panel.tool-panel.panel-bottom.native-key-bindings.script-view)
     -1:37.4.0 script:kill-process (div.am-panel.tool-panel.panel-bottom.native-key-bindings.script-view)
     -1:29.2.0 script:close-view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:07.8.0 core:cancel (div.am-panel.tool-panel.panel-bottom.native-key-bindings.script-view)
```

### Non-Core Packages

```
script 3.25.0 
```

**Comment by pfandzelter** [comment]
Hey everyone, this is a known issue as reported in #2002 and #1997. The PR #2004 should fix this (feel free to try that out). Unfortunately so far none of the maintainers have merged it or made a new release for the package.

**Comment by misterchalm22** [comment]
> 
> 
> Hey everyone, this is a known issue as reported in #2002 and #1997. The PR #2004 should fix this (feel free to try that out). Unfortunately so far none of the maintainers have merged it or made a new release for the package.

That's fine, but how would one implement this without building their own version of Atom based on this commit? Maintainers need to fix this error, especially if it is as simple as it looks.

`TypeError: Cannot read property 'remove' of undefined
    at ScriptView.MessagePanelView.remove (C:\Users\travc\.atom\packages\script\node_modules\atom-message-panel\lib\MessagePanelView.js:189:30)
    at ScriptView.detach (C:\Users\travc\.atom\packages\script\node_modules\jquery\dist\jquery.js:5357:15)
    at ScriptView.removePanel (file:///C:/Users/travc/.atom/packages/script/lib/script-view.js:89:10)
    at Object.closeScriptViewAndStopRunner (file:///C:/Users/travc/.atom/packages/script/lib/script.js:161:21)
    at HTMLElement.scriptCloseView (file:///C:/Users/travc/.atom/packages/script/lib/script.js:94:39)
    at CommandRegistry.handleCommandEvent (C:\Users\travc\AppData\Local\atom\app-1.42.0\resources\app\static\<embedded>:11:349385)
    at CommandRegistry.dispatch (C:\Users\travc\AppData\Local\atom\app-1.42.0\resources\app\static\<embedded>:11:347860)
    at ScriptView.close (file:///C:/Users/travc/.atom/packages/script/lib/script-view.js:99:19)
    at HTMLDivElement.<anonymous> (C:\Users\travc\.atom\packages\script\node_modules\space-pen\lib\space-pen.js:220:36)
    at HTMLDivElement.dispatch (C:\Users\travc\.atom\packages\script\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (C:\Users\travc\.atom\packages\script\node_modules\jquery\dist\jquery.js:4121:28)`

**Comment by renato-milan-latam-com** [comment]
Same here.

**Comment by bekaertruben** [comment]
same.

**Comment by lienzz** [comment]
Got the same issue.

**Comment by evanlandreneau** [comment]
Same here.

**Comment by overly-excessive** [comment]
same issue on Manjaro Linux

**Comment by rubenayla** [comment]
The same. Trying to stop the execution of a python program that recognizes the tone of the sound from the mic, and prints the result.

**Comment by vtsu3** [comment]
same

**Comment by radix-soup** [comment]
same

**Comment by alekks** [comment]
Same for me. 
**Atom**: 1.42.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.25.0

**Comment by Sonderwoods** [comment]
solved with this fix:

https://github.com/tcarlsen/atom-message-panel/pull/90/commits/529dcb5a97c7cf90f54b2d8c1811d3f97dd3835b

**Comment by marcelinollano** [comment]
@Sonderwoods it sorta fixes it, because now if you close the panel clicking the `x` then try to run again and never opens again.

**Comment by marcelinollano** [comment]
I found this comment to work for me https://github.com/rgbkrk/atom-script/issues/1984#issuecomment-553515197

**Comment by JaySep** [comment]
Same here..
Atom : 1.42.0
Script : 3.25.0
OS : Win10 Pro

**Comment by iamoshiro** [comment]
@Sonderwoods it`s work thanks!

**Comment by pensierinmusica** [comment]
What @Sonderwoods proposes doesn't work. If you close the window then you can't open it again.

**Comment by pensierinmusica** [comment]
@rgbkrk any chance to see this fixed?

**Comment by xl33** [comment]
It's not a problem with the package itself. It comes from atom doesn't know where the scripts are. I have multiple problems with all packages at the moment and the reason is atom can't find the path of the package location

**Comment by pfandzelter** [comment]
> What @Sonderwoods proposes doesn't work. If you close the window then you can't open it again.

It doesn't as the current code only creates a view on the first run, not again after you close it. You can see the code [here](https://github.com/rgbkrk/atom-script/blob/f95743f3fa94c30673637b7f81b907a6e45fc475/lib/script-view.js#L77). Hence the fix is to create the view every time you run a script. That is not necessarily a bug in [carlsen/atom-message-panel](https://github.com/tcarlsen/atom-message-panel/issues/92) (in fact I think this is the opposite of a bug: script stopped working when a bug on their side was fixed).

**Comment by pensierinmusica** [comment]
@pfandzelter so maybe `atom-script` should be modified to re-create a view if the previous one has been closed?

**Comment by pfandzelter** [comment]
@pensierinmusica That's what I think as well, hence [this change](https://github.com/rgbkrk/atom-script/blob/38134ec497b820d68108e3f175e02777a290d1a1/lib/script-view.js#L77) in #2004

**Comment by guptacharchil** [comment]
same in ubunto also

**Comment by TheRealMRMango** [comment]
Same here
[Enter steps to reproduce:]

1. ...Esc

**Atom**: 1.43.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.2
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.25.0


### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of undefined

```
At /Users/siyandamsimango/.atom/packages/script/node_modules/atom-message-panel/lib/MessagePanelView.js:189

TypeError: Cannot read property 'remove' of undefined
    at ScriptView.MessagePanelView.remove (/packages/script/node_modules/atom-message-panel/lib/MessagePanelView.js:189:30)
    at ScriptView.detach (/packages/script/node_modules/jquery/dist/jquery.js:5357:15)
    at ScriptView.removePanel (/packages/script/lib/script-view.js:89:10)
    at Object.closeScriptViewAndStopRunner (/packages/script/lib/script.js:161:21)
    at HTMLElement.coreCancel (/packages/script/lib/script.js:92:33)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349290)
    at KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1253549)
    at KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1249683)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:284496)
```

### Commands

```
  8x -1:41.9.0 script:run (input.hidden-input)
     -1:06.9.0 script:close-view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:03.3.0 core:cancel (a.btn-copy-report.icon.icon-clippy)
```

### Non-Core Packages

```
script 3.25.0 
```

**Comment by EyeOdin** [comment]
Same here

**Comment by jameswilliams1** [comment]
Also get this when closing script:
```js
/home/james/.atom/packages/script/node_modules/atom-message-panel/lib/MessagePanelView.js:189
Hide Stack Trace
TypeError: Cannot read property 'remove' of undefined
    at ScriptView.MessagePanelView.remove (/home/james/.atom/packages/script/node_modules/atom-message-panel/lib/MessagePanelView.js:189:30)
    at ScriptView.detach (/home/james/.atom/packages/autocomplete-python/node_modules/jquery/dist/jquery.js:5357:15)
    at ScriptView.removePanel (/home/james/.atom/packages/script/lib/script-view.js:89:10)
    at Object.closeScriptViewAndStopRunner (/home/james/.atom/packages/script/lib/script.js:161:21)
    at HTMLElement.scriptCloseView (/home/james/.atom/packages/script/lib/script.js:94:39)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:349290)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/static/<embedded>:11:347765)
    at ScriptView.close (/home/james/.atom/packages/script/lib/script-view.js:99:19)
    at HTMLDivElement.<anonymous> (/home/james/.atom/packages/autocomplete-python/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLDivElement.dispatch (/home/james/.atom/packages/autocomplete-python/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/home/james/.atom/packages/autocomplete-python/node_modules/jquery/dist/jquery.js:4121:28)
```
System:
```bash
Distributor ID:	Debian
Description:	Debian GNU/Linux bullseye/sid
Release:	testing
Codename:	bullseye
```
Atom:
```bash
Atom    : 1.43.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```
Window refuses to close until atom is restarted after any code has been ran.

**Comment by aminya** [comment]
Does this still happen?

**Comment by LoseUFaith** [comment]
click the X button just close the UI frame but the running process won't since this issue open........

**Comment by LoseUFaith** [comment]
Is that a feature?

**Comment by Clumsyoof** [comment]
this problem is currently being faced in java by me and the above mentioned fixes dont work
Atom: 1.58.0 64x
Electron: 12.0.11
OS: Windows 10 pro 21H1 19043.1348 64x
Thrown From: script package 3.32.2
Stack trace-
TypeError: Cannot read property 'includes' of undefined
^C
