### ISSUE TITLE
Uncaught TypeError: Cannot read property "remove" of undefined

### ISSUE THREAD

**Issue by Ochitsuku** [atom-ide-community/atom-script#2024]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.42.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.25.0

### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of undefined

```
At C:\Users\RaphaelNeuherz\.atom\packages\script\node_modules\atom-message-panel\lib\MessagePanelView.js:189

TypeError: Cannot read property 'remove' of undefined
    at ScriptView.MessagePanelView.remove (/packages/script/node_modules/atom-message-panel/lib/MessagePanelView.js:189:30)
    at ScriptView.detach (/packages/git-plus/node_modules/jquery/dist/jquery.js:5357:15)
    at ScriptView.removePanel (/packages/script/lib/script-view.js:89:10)
    at Object.closeScriptViewAndStopRunner (/packages/script/lib/script.js:161:21)
    at HTMLElement.scriptCloseView (/packages/script/lib/script.js:94:39)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:349385)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:347860)
    at ScriptView.close (/packages/script/lib/script-view.js:99:19)
    at /packages/git-plus/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLDivElement.dispatch (/packages/git-plus/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/git-plus/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
 25x -6:54.2.0 core:move-down (input.hidden-input)
  3x -4:12 fuzzy-finder:toggle-git-status-finder (textarea.)
     -3:11.8.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-atom-dark-ui)
     -2:02.3.0 core:confirm (input.hidden-input)
     -0:25.2.0 script:run (input.hidden-input)
  2x -0:17.8.0 script:close-view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-atom-dark-ui)
```

### Non-Core Packages

```
git-plus 8.7.1 
script 3.25.0 
vk-terminal 3.0.1 
```

How is this fixable?

**Comment by antihero008** [comment]
I just updated "script" to the latest version.It has not even been a minute and I cannot use "Ctrl+w" to close the tab after using "Ctrl+Shift+B".

**Comment by aminya** [comment]
Fixed by updating "atom-message-panel"
