### ISSUE TITLE
Uncaught TypeError: Cannot read property 'remove' of undefined

### ISSUE THREAD

**Issue by zerxdapro** [atom-ide-community/atom-script#2038]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.43.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.25.0

### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of undefined

```
At C:\Users\micha\.atom\packages\script\node_modules\atom-message-panel\lib\MessagePanelView.js:189

TypeError: Cannot read property 'remove' of undefined
    at ScriptView.MessagePanelView.remove (/packages/script/node_modules/atom-message-panel/lib/MessagePanelView.js:189:30)
    at ScriptView.detach (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:5357:15)
    at ScriptView.removePanel (/packages/script/lib/script-view.js:89:10)
    at Object.closeScriptViewAndStopRunner (/packages/script/lib/script.js:161:21)
    at HTMLElement.coreCancel (/packages/script/lib/script.js:92:33)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.43.0/resources/app/static/<embedded>:11:349290)
    at KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.43.0/resources/app/static/<embedded>:11:1253549)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.43.0/resources/app/static/<embedded>:11:1249683)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.43.0/resources/app/static/<embedded>:11:284496)
```

### Commands

```
     -0:08.3.0 editor:consolidate-selections (input.hidden-input)
     -0:08.3.0 core:cancel (input.hidden-input)
     -0:08.1.0 editor:consolidate-selections (input.hidden-input)
     -0:08.1.0 core:cancel (input.hidden-input)
     -0:08.0 editor:consolidate-selections (input.hidden-input)
     -0:08.0 core:cancel (input.hidden-input)
     -0:07.8.0 editor:consolidate-selections (input.hidden-input)
     -0:07.8.0 core:cancel (input.hidden-input)
     -0:07.6.0 editor:consolidate-selections (input.hidden-input)
     -0:07.6.0 core:cancel (input.hidden-input)
     -0:07.4.0 editor:consolidate-selections (input.hidden-input)
     -0:07.4.0 core:cancel (input.hidden-input)
     -0:07.3.0 editor:consolidate-selections (input.hidden-input)
     -0:07.3.0 core:cancel (input.hidden-input)
     -0:06.4.0 editor:consolidate-selections (input.hidden-input)
  2x -0:06.4.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
ide-java 0.9.0 
platformio-ide-terminal 2.10.0 
run 0.0.1 
script 3.25.0 
```

**Comment by pdxwolfy** [comment]
I have this same issue. It crops up after running a script when I try to close the output window.

**Comment by dylansosa** [comment]
Also experiencing this

**Comment by LioisSAD** [comment]
> I have this same issue. It crops up after running a script when I try to close the output window.

Also happens when trying to close any window at all, and when pressing ESC (like to stop highlighting)

**Comment by ubiq-x** [comment]
Same problem.

**Comment by KingHenryV** [comment]
Same issue.

**Comment by ubiq-x** [comment]
For what it's worth, this has worked for me:

https://github.com/rgbkrk/atom-script/issues/1997#issuecomment-557993478

**Comment by NormMacBowden** [comment]
> For what it's worth, this has worked for me: [#1997 (comment)](https://github.com/rgbkrk/atom-script/issues/1997#issuecomment-557993478)

Thanks! Worked.

**Comment by fadhilabdillah** [comment]
which part was it that worked. nothing worked on my atom its fuckin frustating just doing this

**Comment by rnul** [comment]
So is the script project dead? Are there any alternatives that are actively updated?

**Comment by linganzhizhu** [comment]
Have same issue.

**Comment by ubiq-x** [comment]
> which part was it that worked. nothing worked on my atom its fuckin frustating just doing this

It is frustrating, but it's even more frustrating not doing it.  Instructions under the link are pretty clear though.  gl
