### ISSUE TITLE
Uncaught TypeError: Cannot read property 'remove' of undefined

### ISSUE THREAD

**Issue by ss26** [atom-ide-community/atom-script#2065]
### Steps to reproduce

Ran a python script, then tried to close the output screen (output message panel) produced by [script](https://github.com/rgbkrk/atom-script). The output screen did not close and atom threw a popup displaying this error. 

### My setup

**Atom:** 1.41.0 x64
**OS:** Ubuntu 16.04 LTS
**Thrown from:** [script](https://github.com/rgbkrk/atom-script) 3.25.0

### Error Message

Uncaught TypeError: Cannot read property 'remove' of undefined

    /home/valarsundarlis/.atom/packages/script/node_modules/atom-message-panel/lib/MessagePanelView.js:189

### Stack Trace

    TypeError: Cannot read property 'remove' of undefined
        at ScriptView.MessagePanelView.remove (/home/valarsundarlis/.atom/packages/script/node_modules/atom-message-panel/lib/MessagePanelView.js:189:30)
        at ScriptView.detach (/home/valarsundarlis/.atom/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:5357:15)
        at ScriptView.removePanel (/home/valarsundarlis/.atom/packages/script/lib/script-view.js:89:10)
        at Object.closeScriptViewAndStopRunner (/home/valarsundarlis/.atom/packages/script/lib/script.js:161:21)
        at HTMLElement.scriptCloseView (/home/valarsundarlis/.atom/packages/script/lib/script.js:94:39)
        at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:349392)
        at CommandRegistry.dispatch (/usr/share/atom/resources/app/static/<embedded>:11:347867)
        at ScriptView.close (/home/valarsundarlis/.atom/packages/script/lib/script-view.js:99:19)
        at HTMLDivElement.<anonymous> (/home/valarsundarlis/.atom/packages/platformio-ide-terminal/node_modules/space-pen/lib/space-pen.js:220:36)
        at HTMLDivElement.dispatch (/home/valarsundarlis/.atom/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4435:9)
        at HTMLDivElement.elemData.handle (/home/valarsundarlis/.atom/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4121:28)

### Non-Core packages

    script 3.25.0
    python-autopep8 0.1.3
    platformio-ide-terminal 2.10.0
    minimap 4.29.9
    linter-ui-default 1.8.1
    linter-flake8 2.4.0
    linter 2.3.1
    kite 0.178.0
    intentions 1.1.5
    file-icons 2.1.39
    busy-signal 2.0.1
    autocomplete-python 1.16.0

**Comment by RAB-hub** [comment]
Also have this error, same description as original poster. 
Only difference is I am using an older version of Atom 1.28.0
Looks like this issue has been around for quite a number of versions.

**Comment by Qboi123** [comment]
Also on Windows 10 version 1909

**Comment by Catullo99** [comment]
I have the same problem, using Linux Mint 19 and Atom 1.44. I think this is a general issue...

**Comment by 12mohaned** [comment]
I had some the problem, using Unix and Atom 1.34, I tried changing my path in .bash_profile to look to the installed packages required for running go but it didn't work

**Comment by StendertBroos** [comment]
it's a bug
1. uninstall the package script, 
2. install older version by running in terminal: 
`apm install script@3.18.1
`
then, run a script. If there are errors, click the red icon in the bottom right, and click recompile in the top right.
Done!
