### ISSUE TITLE
Uncaught TypeError: Cannot read property 'remove' of undefined

### ISSUE THREAD

**Issue by kznww** [atom-ide-community/atom-script#2066]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.25.0

### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of undefined

```
At C:\Users\denis\.atom\packages\script\node_modules\atom-message-panel\lib\MessagePanelView.js:189

TypeError: Cannot read property 'remove' of undefined
    at ScriptView.MessagePanelView.remove (/packages/script/node_modules/atom-message-panel/lib/MessagePanelView.js:189:30)
    at ScriptView.detach (/packages/script/node_modules/jquery/dist/jquery.js:5357:15)
    at ScriptView.removePanel (/packages/script/lib/script-view.js:89:10)
    at Object.closeScriptViewAndStopRunner (/packages/script/lib/script.js:161:21)
    at HTMLElement.scriptCloseView (/packages/script/lib/script.js:94:39)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:349290)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:347765)
    at ScriptView.close (/packages/script/lib/script-view.js:99:19)
    at /packages/script/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLDivElement.dispatch (/packages/script/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/script/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:52.3.0 core:cancel (input.hidden-input)
     -0:52.1.0 editor:consolidate-selections (input.hidden-input)
     -0:52.1.0 core:cancel (input.hidden-input)
     -0:52 editor:consolidate-selections (input.hidden-input)
     -0:52 core:cancel (input.hidden-input)
     -0:51.8.0 editor:consolidate-selections (input.hidden-input)
  3x -0:51.8.0 core:cancel (input.hidden-input)
     -0:39.6.0 script:run (input.hidden-input)
     -0:35.3.0 script:close-view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:18.1.0 core:select-all (input.hidden-input)
  5x -0:18 core:backspace (input.hidden-input)
     -0:08.5.0 core:move-right (input.hidden-input)
     -0:06.8.0 editor:newline (input.hidden-input)
  2x -0:05.6.0 core:backspace (input.hidden-input)
     -0:04.8.0 editor:newline (input.hidden-input)
  3x -0:01.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-discord 2.0.2 
script 3.25.0 
```

**Comment by ryankshah** [comment]
I am also having the same problem!

### Steps to Reproduce

1. Run a python script on Atom
2. Once finished, try and close the build console window (tada!)
3. Even trying to press CTRL+W or similar key patterns also throws the same error!

### Platform Specs 

Atom: 1.44.0 x64
Electron: 4.2.7
OS: Microsoft Windows 10
Thrown From: script package 3.25.0

### Stack Trace

C:\Users\xwb18152\.atom\packages\script\node_modules\atom-message-panel\lib\MessagePanelView.js:189
Hide Stack Trace
TypeError: Cannot read property 'remove' of undefined
    at ScriptView.MessagePanelView.remove (C:\Users\xwb18152\.atom\packages\script\node_modules\atom-message-panel\lib\MessagePanelView.js:189:30)
    at ScriptView.detach (C:\Users\xwb18152\.atom\packages\pdf-view\node_modules\jquery\dist\jquery.js:5357:15)
    at ScriptView.removePanel (file:///C:/Users/xwb18152/.atom/packages/script/lib/script-view.js:89:10)
    at Object.closeScriptViewAndStopRunner (file:///C:/Users/xwb18152/.atom/packages/script/lib/script.js:161:21)
    at HTMLElement.scriptCloseView (file:///C:/Users/xwb18152/.atom/packages/script/lib/script.js:94:39)
    at CommandRegistry.handleCommandEvent (C:\Users\xwb18152\AppData\Local\atom\app-1.44.0\resources\app\static\<embedded>:11:349290)
    at CommandRegistry.dispatch (C:\Users\xwb18152\AppData\Local\atom\app-1.44.0\resources\app\static\<embedded>:11:347765)
    at ScriptView.close (file:///C:/Users/xwb18152/.atom/packages/script/lib/script-view.js:99:19)
    at HTMLDivElement.<anonymous> (C:\Users\xwb18152\.atom\packages\pdf-view\node_modules\space-pen\lib\space-pen.js:220:36)
    at HTMLDivElement.dispatch (C:\Users\xwb18152\.atom\packages\pdf-view\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (C:\Users\xwb18152\.atom\packages\pdf-view\node_modules\jquery\dist\jquery.js:4121:28)

**Comment by adscregg** [comment]
Same issue here

### Steps to reproduce:

1. Run a python script on Atom
2. Once finished, try and close the console window

### Platform Specs

Atom: 1.44.0 x64
Electron: 4.2.7
OS: Microsoft Windows 10 Home
Thrown From: [script](https://github.com/rgbkrk/atom-script) package 3.25.0


### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of undefined

```
At C:\Users\Anthony\.atom\packages\script\node_modules\atom-message-panel\lib\MessagePanelView.js:189

TypeError: Cannot read property 'remove' of undefined
    at ScriptView.MessagePanelView.remove (/packages/script/node_modules/atom-message-panel/lib/MessagePanelView.js:189:30)
    at ScriptView.detach (/packages/autocomplete-python/node_modules/jquery/dist/jquery.js:5357:15)
    at ScriptView.removePanel (/packages/script/lib/script-view.js:89:10)
    at Object.closeScriptViewAndStopRunner (/packages/script/lib/script.js:161:21)
    at HTMLElement.scriptCloseView (/packages/script/lib/script.js:94:39)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:349290)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:347765)
    at ScriptView.close (/packages/script/lib/script-view.js:99:19)
    at /packages/autocomplete-python/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLDivElement.dispatch (/packages/autocomplete-python/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/autocomplete-python/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -1:02.6.0 settings-view:uninstall-packages (input.hidden-input)
     -0:48.4.0 editor:toggle-line-comments (input.hidden-input)
     -0:47.1.0 script:run (input.hidden-input)
     -0:42.7.0 script:close-view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-atom-dark-ui)
```

### Non-Core Packages

```
autocomplete-python 1.16.0 
file-icons 2.1.39 
highlight-selected 0.17.0 
minimap 4.29.9 
python-autopep8 0.1.3 
script 3.25.0 
```

**Comment by harmonicus** [comment]
Same

[Enter steps to reproduce:]


    Run a python script on Atom
    Once finished, try and close the console window by CTRL+W


**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Debian GNU/Linux
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.25.0


### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of undefined

```
At /home/mx/.atom/packages/script/node_modules/atom-message-panel/lib/MessagePanelView.js:189

TypeError: Cannot read property 'remove' of undefined
    at ScriptView.MessagePanelView.remove (/packages/script/node_modules/atom-message-panel/lib/MessagePanelView.js:189:30)
    at ScriptView.detach (/packages/build/node_modules/jquery/dist/jquery.js:5357:15)
    at ScriptView.removePanel (/packages/script/lib/script-view.js:89:10)
    at Object.closeScriptViewAndStopRunner (/packages/script/lib/script.js:161:21)
    at HTMLElement.scriptCloseView (/packages/script/lib/script.js:94:39)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:349290)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/static/<embedded>:11:347765)
    at ScriptView.close (/packages/script/lib/script-view.js:99:19)
    at /packages/build/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLDivElement.dispatch (/packages/build/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/build/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -2:59.4.0 intentions:highlight (input.hidden-input)
     -2:58.9.0 core:save (input.hidden-input)
     -2:48 grammar-selector:show (atom-text-editor.editor.is-focused)
     -2:37.3.0 intentions:highlight (input.hidden-input)
     -2:37.2.0 core:save (input.hidden-input)
  2x -2:34.3.0 core:backspace (input.hidden-input)
     -2:29.8.0 intentions:highlight (input.hidden-input)
     -2:29.7.0 core:save (input.hidden-input)
     -2:19.4.0 intentions:highlight (input.hidden-input)
     -2:18 core:save (input.hidden-input)
     -2:17.5.0 intentions:highlight (input.hidden-input)
     -2:17.2.0 script:run (input.hidden-input)
     -2:14.1.0 intentions:highlight (input.hidden-input)
     -2:13.5.0 script:run (input.hidden-input)
     -1:38.4.0 application:open-your-stylesheet (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:21.8.0 script:close-view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
autocomplete-clang 0.13.0 
build 0.70.0 
busy-signal 2.0.1 
file-icons 2.1.39 
intentions 1.1.5 
language-ini 1.23.0 
linter 2.3.1 
linter-gcc2 0.8.8 
linter-ui-default 1.8.1 
platformio-ide 2.6.0 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.10.0 
script 3.25.0 
tool-bar 1.2.0 
```

**Comment by DFGeerdink** [comment]
Have had this for a while now..

[Enter steps to reproduce:]

1. Run a python3 script in Atom
2. Once finished, try and close the console window by CTRL+W or pressing the close button

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Ubuntu 18.04.4
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.25.0


### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of undefined

```
At /home/rambo/.atom/packages/script/node_modules/atom-message-panel/lib/MessagePanelView.js:189

TypeError: Cannot read property 'remove' of undefined
    at ScriptView.MessagePanelView.remove (/packages/script/node_modules/atom-message-panel/lib/MessagePanelView.js:189:30)
    at ScriptView.detach (/packages/script/node_modules/jquery/dist/jquery.js:5357:15)
    at ScriptView.removePanel (/packages/script/lib/script-view.js:89:10)
    at Object.closeScriptViewAndStopRunner (/packages/script/lib/script.js:161:21)
    at HTMLElement.scriptCloseView (/packages/script/lib/script.js:94:39)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:349123)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/static/<embedded>:11:347598)
    at ScriptView.close (/packages/script/lib/script-view.js:99:19)
    at /packages/script/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLDivElement.dispatch (/packages/script/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/script/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
 33x -9:46.9.0 core:undo (input.hidden-input)
     -9:44.5.0 core:save (input.hidden-input)
     -8:57.3.0 open-terminal-here:open (span.name.icon.icon-file-directory)
     -5:37 tree-view:collapse-all (span.name.icon.icon-repo)
     -1:29.2.0 script:close-view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-touch-events 0.23.0 
emmet 2.4.3 
kite 0.178.0 
minimap 4.29.9 
minimap-pigments 0.2.2 
open-recent 5.0.0 
open-terminal-here 2.3.2 
pigments 0.40.2 
**script 3.25.0** 
tabs-to-spaces 1.0.5 
```

**Comment by julibeg** [comment]
This is a quite common issue and a temporary fix has been posted earlier: https://github.com/rgbkrk/atom-script/issues/1997#issuecomment-557993478

**Comment by Xelbayria** [comment]
I have the same issue shown in post#2 posted by ryankshah. I had to disable the script addon for now. I don't have Electron 4.2.7 addon. I don't have:
 .atom\packages\script\node_modules\atom-message-panel\lib\MessagePanelView.js
😭 I can't use a temporary solution from the link: #1997 (comment)

**Comment by stormerthe2nd** [comment]
[Enter steps to reproduce:]

1. ... Everytime closing the terminal
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.25.0


### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of undefined

```
At C:\Users\91797\.atom\packages\script\node_modules\atom-message-panel\lib\MessagePanelView.js:189

TypeError: Cannot read property 'remove' of undefined
    at ScriptView.MessagePanelView.remove (/packages/script/node_modules/atom-message-panel/lib/MessagePanelView.js:189:30)
    at ScriptView.detach (/packages/script/node_modules/jquery/dist/jquery.js:5357:15)
    at ScriptView.removePanel (/packages/script/lib/script-view.js:89:10)
    at Object.closeScriptViewAndStopRunner (/packages/script/lib/script.js:161:21)
    at HTMLElement.scriptCloseView (/packages/script/lib/script.js:94:39)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:349290)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:347765)
    at ScriptView.close (/packages/script/lib/script-view.js:99:19)
    at /packages/script/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLDivElement.dispatch (/packages/script/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/script/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -4:40.1.0 core:save (input.hidden-input)
     -4:37 intentions:highlight (input.hidden-input)
     -4:36.5.0 script:run-by-line-number (input.hidden-input)
  2x -4:27.2.0 intentions:highlight (input.hidden-input)
     -4:25.5.0 script:run-by-line-number (input.hidden-input)
     -4:21.9.0 intentions:highlight (input.hidden-input)
  2x -4:17.8.0 core:backspace (input.hidden-input)
     -4:16.5.0 intentions:highlight (input.hidden-input)
     -4:16.3.0 core:undo (input.hidden-input)
     -4:14.8.0 core:backspace (input.hidden-input)
     -4:14 intentions:highlight (input.hidden-input)
     -4:13.6.0 core:save (input.hidden-input)
     -3:39.7.0 core:backspace (input.hidden-input)
  7x -3:37.3.0 intentions:highlight (input.hidden-input)
  2x -3:36.1.0 core:undo (input.hidden-input)
  2x -3:25.9.0 script:close-view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
autocomplete-python 1.16.0 
busy-signal 2.0.1 
darker-one-dark-syntax 1.1.0 
file-icons 2.1.39 
intentions 1.1.5 
linter 2.3.1 
linter-flake8 2.4.0 
linter-ui-default 1.8.1 
minimap 4.29.9 
platformio-ide-terminal 2.10.0 
predawn-syntax 1.0.4 
python-autopep8 0.1.3 
script 3.25.0 
```

**Comment by Nemo-Nowane** [comment]
`Same issue

1. Run a script
2. Try to close script panel

**Atom**: 1.45.0 x64
**Electron**: 4.2.12
**OS**: "Manjaro Linux 19.0.2"
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.25.0


`### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of undefined

```
At /home/ahs-nn/.atom/packages/script/node_modules/atom-message-panel/lib/MessagePanelView.js:189

TypeError: Cannot read property 'remove' of undefined
    at ScriptView.MessagePanelView.remove (/packages/script/node_modules/atom-message-panel/lib/MessagePanelView.js:189:30)
    at ScriptView.detach (/packages/script/node_modules/jquery/dist/jquery.js:5357:15)
    at ScriptView.removePanel (/packages/script/lib/script-view.js:89:10)
    at Object.closeScriptViewAndStopRunner (/packages/script/lib/script.js:161:21)
    at HTMLElement.scriptCloseView (/packages/script/lib/script.js:94:39)
    at CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:405:43)
    at CommandRegistry.dispatch (/usr/lib/atom/src/command-registry.js:292:17)
    at ScriptView.close (/packages/script/lib/script-view.js:99:19)
    at /packages/script/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLDivElement.dispatch (/packages/script/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/script/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  2x -9:27.4.0 core:move-left (input.hidden-input)
 11x -9:26.2.0 core:backspace (input.hidden-input)
     -8:47.8.0 editor:newline (input.hidden-input)
  6x -8:36.5.0 core:move-left (input.hidden-input)
  7x -8:31.5.0 core:move-right (input.hidden-input)
     -8:29.3.0 core:move-left (input.hidden-input)
     -7:39.6.0 core:move-right (input.hidden-input)
     -7:02.7.0 core:move-left (input.hidden-input)
  7x -6:59.4.0 core:backspace (input.hidden-input)
     -6:01.7.0 core:move-right (input.hidden-input)
 12x -5:55.4.0 core:move-left (input.hidden-input)
     -5:01.6.0 core:copy (input.hidden-input)
     -5:00.4.0 editor:newline (input.hidden-input)
     -4:59.5.0 core:backspace (input.hidden-input)
     -4:57.8.0 core:paste (input.hidden-input)
     -4:35.5.0 script:close-view (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-atom-material-ui.find-visible)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
file-icons 2.1.39 
gdb-debug 0.0.3 
language-rust 0.4.12 
minimap 4.29.9 
minimap-autohide 0.10.1 
python-tools 0.6.9 
script 3.25.0 
```

`

**Comment by hollossy** [comment]
Same here!

**Comment by SirTypesALot** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.4
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.25.0


### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of undefined

```
At /Users/marczhoutoneu/.atom/packages/script/node_modules/atom-message-panel/lib/MessagePanelView.js:189

TypeError: Cannot read property 'remove' of undefined
    at ScriptView.MessagePanelView.remove (/packages/script/node_modules/atom-message-panel/lib/MessagePanelView.js:189:30)
    at ScriptView.detach (/packages/todo-show/node_modules/jquery/dist/jquery.js:5357:15)
    at ScriptView.removePanel (/packages/script/lib/script-view.js:89:10)
    at Object.closeScriptViewAndStopRunner (/packages/script/lib/script.js:161:21)
    at HTMLElement.scriptCloseView (/packages/script/lib/script.js:94:39)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349290)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:347765)
    at ScriptView.close (/packages/script/lib/script-view.js:99:19)
    at /packages/todo-show/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLDivElement.dispatch (/packages/todo-show/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/todo-show/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  2x -7:55.1.0 core:move-left (input.hidden-input)
     -1:43 editor:newline (input.hidden-input)
  7x -1:38 core:backspace (input.hidden-input)
     -1:26.5.0 core:save (input.hidden-input)
  3x -1:19.9.0 script:close-view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.teletype-Authenticated)
     -1:11.8.0 script:run (div.am-panel.tool-panel.panel-bottom.native-key-bindings.script-view)
     -1:10.1.0 script:kill-process (div.am-panel.tool-panel.panel-bottom.native-key-bindings.script-view)
```

### Non-Core Packages

```
atom-clock 0.1.17 
busy-signal 2.0.1 
highlight-selected 0.17.0 
intentions 1.1.5 
language-latex 1.2.0 
language-latexsimple 0.12.1 
latex 0.50.2 
linter 2.3.1 
linter-gcc 0.9.0 
linter-pyflakes 0.3.2 
linter-pylama 0.10.1 
linter-python 3.1.2 
linter-python-pep257 0.0.1 
linter-python-pep8 0.2.0 
linter-ui-default 1.8.1 
minimap 4.29.9 
minimap-codeglance 0.4.7 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
pdf-view 0.72.0 
quick-query-sqlite 0.3.2 
script 3.25.0 
teletype 0.13.4 
todo-show 2.3.2 
vk-terminal 3.0.1 
wakatime 9.0.2 
```
