### ISSUE TITLE
Uncaught TypeError: Cannot read property 'remove' of undefined

### ISSUE THREAD

**Issue by kevinpulido89** [atom-ide-community/atom-script#2085]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.25.0

### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of undefined

```
At C:\Users\Kevin Pulido\.atom\packages\script\node_modules\atom-message-panel\lib\MessagePanelView.js:189

TypeError: Cannot read property 'remove' of undefined
    at ScriptView.MessagePanelView.remove (/packages/script/node_modules/atom-message-panel/lib/MessagePanelView.js:189:30)
    at ScriptView.detach (/packages/autocomplete-python/node_modules/jquery/dist/jquery.js:5357:15)
    at ScriptView.removePanel (/packages/script/lib/script-view.js:89:10)
    at Object.closeScriptViewAndStopRunner (/packages/script/lib/script.js:161:21)
    at HTMLElement.scriptCloseView (/packages/script/lib/script.js:94:39)
    at CommandRegistry.handleCommandEvent (C:/ProgramData/Kevin Pulido/atom/app-1.45.0/resources/app/static/<embedded>:11:349290)
    at CommandRegistry.dispatch (C:/ProgramData/Kevin Pulido/atom/app-1.45.0/resources/app/static/<embedded>:11:347765)
    at ScriptView.close (/packages/script/lib/script-view.js:99:19)
    at /packages/autocomplete-python/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLDivElement.dispatch (/packages/autocomplete-python/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/autocomplete-python/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -5:44.5.0 editor:newline (input.hidden-input)
     -5:44.3.0 core:paste (input.hidden-input)
  2x -5:43.1.0 core:move-left (input.hidden-input)
  4x -5:42 core:backspace (input.hidden-input)
  2x -5:31.9.0 core:move-left (input.hidden-input)
  2x -5:31.4.0 core:move-right (input.hidden-input)
     -5:29.9.0 core:backspace (input.hidden-input)
  2x -5:29.2.0 core:move-left (input.hidden-input)
     -5:28.3.0 core:move-down (input.hidden-input)
  5x -5:28.1.0 core:move-left (input.hidden-input)
     -5:05.4.0 script:run (input.hidden-input)
  2x -3:33.4.0 core:backspace (input.hidden-input)
     -3:23.2.0 script:run (input.hidden-input)
     -2:37.6.0 core:backspace (input.hidden-input)
  2x -1:52.4.0 core:save (input.hidden-input)
     -0:13.1.0 script:close-view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
autocomplete-python 1.16.0 
ide-python 1.5.0 
kite 0.178.0 
script 3.25.0 
```

**Comment by tgww** [comment]
I have the same thing:

ubuntu 19.10

atom-ide-ui 0.13.0 
autocomplete-python 1.16.0 
ide-python 1.5.0 
kite 0.178.0 
script 3.25.0

**Comment by joshbduncan** [comment]
Having the same issue. After running script I can't close the script output screen at all. Tested on Python files.

macOS 10.15.3

autocomplete-python 1.16.0
python-autopep8 0.1.3
linter-flake8 2.4.0
script 3.25.0

**Comment by Meenit** [comment]
Also having the same issue.

Windows 10 10.0.18362 Build 18362

```
autocomplete-python 1.16.0 
ide-python 1.5.0 
kite 0.178.0 
script 3.25.0 
```

**Comment by FlexCode29** [comment]
Oh cmon someone find a solution that's a pain in the ass

**Comment by mathgru** [comment]
I am having the same problem.

**Comment by sah-py** [comment]
same

**Comment by xunoaib** [comment]
To add some information, I get this error if I press escape while the Python output window has focus. I tried adding a very naive check of `if (index === undefined) return;` to MessagePanelView.js:189  which suppresses the error but causes the output panel to disappear.

**Comment by shakeelansari63** [comment]
> To add some information, I get this error if I press escape while the Python output window has focus. I tried adding a very naive check of `if (index != undefined)` to `MessagePanelView.js:189` which suppresses the error but causes the output panel to disappear.

This Solution worked for me
