### ISSUE TITLE
Failed to activate the script package

### ISSUE THREAD

**Issue by Lea313** [atom-ide-community/atom-script#2090]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.25.0

### Stack Trace

Failed to activate the script package

```
At Cannot find module 'uuid'

Error: Cannot find module 'uuid'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.45.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:146745)
    at /packages/atom-script/lib/grammar-utils.js:6:24)
    at /packages/atom-script/lib/grammar-utils.js:109:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:146745)
    at /packages/atom-script/lib/grammars/index.coffee:5:45)
    at /packages/atom-script/lib/grammars/index.coffee:4:1)
    at /packages/atom-script/lib/grammars/index.coffee:4:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:146745)
    at /packages/atom-script/lib/grammars.js:9:28)
    at /packages/atom-script/lib/grammars.js:1:13)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
```

### Commands

```
     -0:59.3.0 github:toggle-github-tab-focus (atom-pane.pane.active)
     -0:50.1.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:43.5.0 core:confirm (input.hidden-input)
     -0:37.4.0 autocomplete-plus:confirm (input.hidden-input)
     -0:37.4.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:35 autocomplete-plus:confirm (input.hidden-input)
     -0:35 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:27.7.0 script:run (input.hidden-input)
```

### Non-Core Packages

```
script 3.25.0 
atom-script-master undefined 
```

**Comment by igotbitches** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.50.0 x64
**Electron**: 5.0.13
**OS**: Unknown Windows version
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.26.0


### Stack Trace

Failed to activate the script package

```
At Cannot find module 'uuid'
Require stack:
- C:\Users\check\.atom\packages\atom-script\lib\grammar-utils.js
- C:\Users\check\.atom\packages\atom-script\lib\grammars\index.coffee
- C:\Users\check\.atom\packages\atom-script\lib\grammars.js
- C:\Users\check\.atom\packages\atom-script\lib\code-context-builder.js
- C:\Users\check\.atom\packages\atom-script\lib\script.js
- C:\Users\check\AppData\Local\atom\app-1.50.0\resources\app.asar\static\index.html

Error: Cannot find module 'uuid'
Require stack:
- C:\Users\check\.atom\packages\atom-script\lib\grammar-utils.js
- C:\Users\check\.atom\packages\atom-script\lib\grammars\index.coffee
- C:\Users\check\.atom\packages\atom-script\lib\grammars.js
- C:\Users\check\.atom\packages\atom-script\lib\code-context-builder.js
- C:\Users\check\.atom\packages\atom-script\lib\script.js
- C:\Users\check\AppData\Local\atom\app-1.50.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:683:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.50.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:155481)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:146814)
    at /packages/atom-script/lib/grammar-utils.js:6:24)
    at /packages/atom-script/lib/grammar-utils.js:109:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:146814)
    at /packages/atom-script/lib/grammars/index.coffee:5:45)
    at /packages/atom-script/lib/grammars/index.coffee:4:1)
    at /packages/atom-script/lib/grammars/index.coffee:4:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:146814)
    at /packages/atom-script/lib/grammars.js:9:28)
    at /packages/atom-script/lib/grammars.js:1:13)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:146814)
    at /packages/atom-script/lib/code-context-builder.js:5:41)
    at /packages/atom-script/lib/code-context-builder.js:8:40)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:146814)
    at /packages/atom-script/lib/script.js:3:43)
    at /packages/atom-script/lib/script.js:217:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:1:735013)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:3299534)
    at Package.activateNow (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:3287518)
    at ~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:14:1879
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:1190202)
    at Emitter.emit (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:1191643)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:349412)
    at KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:1230988)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:1227122)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:284829)
```

### Commands

```
     -1:08.4.0 command-palette:toggle (input.hidden-input)
     -1:03.2.0 script:run (input.hidden-input)
```

### Non-Core Packages

```
script 3.26.0 
```

**Comment by Pepita21** [comment]
Am gettin the same erroe

**Comment by Matthewdave** [comment]
does anyone know how to solve this error
