### ISSUE TITLE
Uncaught TypeError: Cannot read property 'remove' of undefined

### ISSUE THREAD

**Issue by CHOW1997** [atom-ide-community/atom-script#2105]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.25.0

### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of undefined

```
At C:\Users\zzter\.atom\packages\script\node_modules\atom-message-panel\lib\MessagePanelView.js:189

TypeError: Cannot read property 'remove' of undefined
    at ScriptView.MessagePanelView.remove (/packages/script/node_modules/atom-message-panel/lib/MessagePanelView.js:189:30)
    at ScriptView.detach (/packages/script/node_modules/jquery/dist/jquery.js:5357:15)
    at ScriptView.removePanel (/packages/script/lib/script-view.js:89:10)
    at Object.closeScriptViewAndStopRunner (/packages/script/lib/script.js:161:21)
    at HTMLElement.scriptCloseView (/packages/script/lib/script.js:94:39)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:349290)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:347765)
    at ScriptView.close (/packages/script/lib/script-view.js:99:19)
    at /packages/script/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLDivElement.dispatch (/packages/script/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/script/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -4:45.9.0 core:paste (input.hidden-input)
     -4:43.6.0 core:undo (input.hidden-input)
 19x -3:31 core:backspace (input.hidden-input)
     -2:22.2.0 core:paste (input.hidden-input)
     -2:17.6.0 script:run (input.hidden-input)
     -2:10.4.0 grammar-selector:show (atom-text-editor.editor.is-focused)
  4x -2:01.6.0 core:backspace (input.hidden-input)
  3x -0:45.6.0 script:close-view (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-one-dark-ui)
  4x -0:40.4.0 core:cancel (div.am-panel.tool-panel.panel-bottom.native-key-bindings.script-view)
```

### Non-Core Packages

```
javascript-snippets 1.2.1 
script 3.25.0 
```

**Comment by indore23** [comment]
same error I am getting too

**Comment by rajb245** [comment]
I get this just pressing the escape key in Atom if script is installed.

**Comment by tada-kun** [comment]
what can i do? install again atom? or what?

**Comment by Mercala** [comment]
Has this been solved?

**Comment by Arego11** [comment]
did someone solve this or no?

**Comment by rajb245** [comment]
I've just uninstalled "script" and am using "Hydrogen" instead for my python needs. I honestly like the notebook style interface better than running the whole script at once. I can't comment on if this has been resolved or not, but no devs have commented here as far as I can tell.

**Comment by LoseUFaith** [comment]
I can use it again after commented the whole "MessagePanelView.prototype.remove()" function in MessagePanelView.js
