### ISSUE TITLE
Uncaught TypeError: Cannot read property 'remove' of undefined

### ISSUE THREAD

**Issue by taxcoder** [atom-ide-community/atom-script#2107]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.25.0

### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of undefined

```
At C:\Users\tanxiang\.atom\packages\script\node_modules\atom-message-panel\lib\MessagePanelView.js:189

TypeError: Cannot read property 'remove' of undefined
    at ScriptView.MessagePanelView.remove (/packages/script/node_modules/atom-message-panel/lib/MessagePanelView.js:189:30)
    at ScriptView.detach (/packages/atom-html-preview/node_modules/jquery/dist/jquery.js:5357:15)
    at ScriptView.removePanel (/packages/script/lib/script-view.js:89:10)
    at Object.closeScriptViewAndStopRunner (/packages/script/lib/script.js:161:21)
    at HTMLElement.scriptCloseView (/packages/script/lib/script.js:94:39)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:349290)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:347765)
    at ScriptView.close (/packages/script/lib/script-view.js:99:19)
    at /packages/atom-html-preview/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLDivElement.dispatch (/packages/atom-html-preview/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/atom-html-preview/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  9x -1:34.6.0 core:move-left (input.hidden-input)
  3x -1:33 core:backspace (input.hidden-input)
     -1:30.3.0 editor:newline-below (input.hidden-input)
  3x -1:28.6.0 core:backspace (input.hidden-input)
     -1:24.2.0 autocomplete-plus:confirm (input.hidden-input)
     -1:24.2.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
  7x -1:19.8.0 core:backspace (input.hidden-input)
 18x -1:09.3.0 core:move-right (input.hidden-input)
  2x -1:07.6.0 editor:newline (input.hidden-input)
     -1:07.1.0 core:move-up (input.hidden-input)
     -1:06.8.0 core:paste (input.hidden-input)
     -1:05.3.0 core:save (input.hidden-input)
     -1:02.2.0 script:run (input.hidden-input)
     -0:32.6.0 core:copy (input.hidden-input)
     -0:31.5.0 core:paste (input.hidden-input)
     -0:08.1.0 script:close-view (atom-workspace.workspace.scrollbars-visible-always.editor-background.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-html-preview 0.2.6 
chinese-translator 1.1.2 
editor-background 1.2.42 
pigments 0.40.2 
script 3.25.0 
simplified-chinese-menu 5.3.5 
```

**Comment by LasseKatten** [comment]
[Same bug posted in an earlier issue](https://github.com/rgbkrk/atom-script/issues/2105)

**Comment by liujun-dlink** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.25.0


### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of undefined

```
At C:\Users\Bruce\.atom\packages\script\node_modules\atom-message-panel\lib\MessagePanelView.js:189

TypeError: Cannot read property 'remove' of undefined
    at ScriptView.MessagePanelView.remove (/packages/script/node_modules/atom-message-panel/lib/MessagePanelView.js:189:30)
    at ScriptView.detach (/packages/atom-ide-terminal/node_modules/jquery/dist/jquery.js:5357:15)
    at ScriptView.removePanel (/packages/script/lib/script-view.js:89:10)
    at Object.closeScriptViewAndStopRunner (/packages/script/lib/script.js:161:21)
    at HTMLElement.coreCancel (/packages/script/lib/script.js:92:33)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:349290)
    at KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:1254747)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:1250881)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:284496)
```

### Commands

```
     -0:32.1.0 editor:consolidate-selections (input.hidden-input)
     -0:32.1.0 core:cancel (input.hidden-input)
     -0:30.3.0 editor:consolidate-selections (input.hidden-input)
     -0:30.3.0 core:cancel (input.hidden-input)
     -0:30 editor:consolidate-selections (input.hidden-input)
     -0:30 core:cancel (input.hidden-input)
     -0:29.8.0 editor:consolidate-selections (input.hidden-input)
     -0:29.8.0 core:cancel (input.hidden-input)
     -0:29.6.0 editor:consolidate-selections (input.hidden-input)
     -0:29.6.0 core:cancel (input.hidden-input)
     -0:29.4.0 editor:consolidate-selections (input.hidden-input)
     -0:29.4.0 core:cancel (input.hidden-input)
     -0:29.2.0 editor:consolidate-selections (input.hidden-input)
     -0:29.2.0 core:cancel (input.hidden-input)
     -0:29 editor:consolidate-selections (input.hidden-input)
     -0:29 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-beautify 0.33.4 
atom-ide-terminal 5.0.1 
node-debug 0.1.7 
run-in-atom 1.0.5 
script 3.25.0 
simple-drag-drop-text 0.5.0 
```

**Comment by liujun-dlink** [comment]
直接将MessagePanelView.js中
MessagePanelView.prototype.remove()
方法整个注释掉后可以正常会用了

**Comment by AaryamanCodes** [comment]
> 直接将MessagePanelView.js中
> MessagePanelView.prototype.remove()
> 方法整个注释掉后可以正常会用了
This means that:
Directly put, MessagePanelView.js
MessagePanelView.prototype.remove()
The method can be used normally after commenting out the whole method
