### ISSUE TITLE
Failed to activate the script package,operation not permitted

### ISSUE THREAD

**Issue by jingjuan** [atom-ide-community/atom-script#698]
[Enter steps to reproduce below:]
1. everytime open atom and active script package even when run atom with administrator permissions.antivirus program has been turned off

**Atom Version**: 1.3.2
**System**: windows 7
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package, v3.2.0
### Stack Trace

Failed to activate the script package

```
At EPERM: operation not permitted, write

Error: EPERM: operation not permitted, write
    at Error (native)
    at Object.fs.writeSync (fs.js:663:20)
    at SyncWriteStream.write (fs.js:1981:6)
    at execSync (child_process.js:491:20)
    at Object.<anonymous> (file:///C:/Users/xxx/.atom/packages/atom-script-master/lib/grammar-utils/coffee-script-compiler.coffee:6:10)
    at Object.<anonymous> (file:///C:/Users/xxxj/.atom/packages/atom-script-master/lib/grammar-utils/coffee-script-compiler.coffee:3:1)
    at Module._compile (C:\Users\xxx\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\xxx\AppData\Local\atom\app-1.3.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\xxx\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/xxx/.atom/packages/atom-script-master/lib/grammar-utils.coffee:69:15)
    at Object.<anonymous> (file:///C:/Users/xxx/.atom/packages/atom-script-master/lib/grammar-utils.coffee:2:1)
    at Module._compile (C:\Users\xxx\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\xxx\AppData\Local\atom\app-1.3.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\xxx\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/xxx/.atom/packages/atom-script-master/lib/grammars.coffee:5:16)
    at Object.<anonymous> (file:///C:/Users/xxx/.atom/packages/atom-script-master/lib/grammars.coffee:4:1)
    at Module._compile (C:\Users\xxx\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\xxx\AppData\Local\atom\app-1.3.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\xxx\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/xxx/.atom/packages/atom-script-master/lib/code-context-builder.coffee:2:14)
    at Object.<anonymous> (file:///C:/Users/xxx/.atom/packages/atom-script-master/lib/code-context-builder.coffee:1:1)
```
### Commands

```
     -0:11.7.0 script:run (atom-text-editor.editor.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
script, v3.2.0

# Dev
No dev packages
```

**Comment by rgbkrk** [comment]
Care to try this again with the latest release?

**Comment by Stormherz** [comment]
@rgbkrk I'm setting up `Script` development environment locally (to help you guys with some issues) - got this error whilte trying to start with `atom -d`, I'll try to see why is this happening, but it would be just great if you have any advice or direction where to start digging =)

**Comment by Stormherz** [comment]
@rgbkrk wow, how very stupid of me not to get all of the dependencies :-\ sorry for bothering =(

**Comment by rgbkrk** [comment]
Hey it's all good! If we're missing dev setup instructions in the README, it would be good to add that in.

**Comment by barthr** [comment]
I'm getting this error all the time, but i have the ansi-to-html package installed. Had to manually install it because of a NPM error, altough script cannot seem to find it

**Comment by DemersM** [comment]
latest script release seems to be unable to install under windows see:  #815 #846 and #881

**Comment by hyst329** [comment]
@DemersM see my comment on #881
